package project.main.games.snake.model;

import java.util.List;

import project.main.games.snake.resource.Settings;
import project.main.games.snake.resource.Sound;

/**
 * Class apple, an apple randomly generated on the screen that the snake can eat to increase their score
 *
 */
public class Apple extends Physical {
	//Type of apple : Normal (score => score + 1) and golden (score => score + 10)
	public enum Type{
		NORMAL(1),GOLDEN(10);
		int score;
		private Type(int _score) {
			score=_score;
		}
	}
	
	private final Type type;

	/**
	 * Constructor
	 * @param _casex number of the case on which the apple is located (according to the x axis)
	 * @param _casey number of the case on which the apple is located (according to the y axis)
	 * @param _type type of the apple (normal or golden)
	 */
	public Apple(double _casex, double _casey, Type _type) {
		super(_casex* Settings.SIZE_CASE, _casey*Settings.SIZE_CASE);
		width=Settings.APPLE_SIZE;
		height=Settings.APPLE_SIZE;
		type=_type;
	}
	
	/**
	 * Return the score earned by the player when the snake eats the apple
	 * @return an integer representing the score earned by the player
	 */
	public int getScore() {
		return getType().score;
	}
	
	/**
	 * Return the type of the apple 
	 * @return the type of the apple
	 */
	public Type getType() {
		return type;
	}
	
	//AUTOGENERATED METHODS
	/**
	 * Enclenched when the snake collides with the apple. The apple is removed from the screen and a new apple is generated
	 */
	@Override
	public int actionCollisionPerso(int arg) {
		// TODO Auto-generated method stub
		this.remove();
		Game.genereApple();
		Game.score+=getScore();
		Sound.COIN.play();
		return 0;
	}

	@Override
	public void calculCollision(List<Physical> objects) {
		// TODO Auto-generated method stub
		
	}

}
